config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "articles#index"
  resources :cars do
    resources :bookings, only: %i[new create update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :starts_at, presence: true
  validates :ends_at, presence: true

  belongs_to :car
  belongs_to :user
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  validates :brand, presence: true
  validates :model, presence: true
  validates :address, presence: true
  validates :price_per_day, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cars, dependent: :destroy
  has_many :bookings, through: :cars, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def new
    @car = Car.find(params[:car_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @car = Car.find(params[:car_id])
    @booking.car = @car
    @booking.user = current_user
    if @booking.save
      @booking.update(accepted: true)
      redirect_to car_path(@car), notice: "Booking request sent!"
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:starts_at, :ends_at, :user_id, :car_id)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def create
    @user = current_user
    @car = Car.new(car_params)
    @car.save
    redirect_to car_path(@car)
  end

  def update
    @car = Car.find(params[:id])
    @car.update(car_params)
    redirect_to car_path(@car)
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path
  end

  private

  def car_params
    params.require(:car).permit(:brand, :model, :year_of_production, :address, :price_per_day, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @cars = Car.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<h2>Book</h2>

<p>We just need some informations to go:</p>

<%= simple_form_for [@car, @booking] do |f| %>
  <%= f.input :starts_at,
              as: :string,
              input_html: { data: { controller: "datepicker" } } %>
  <%= f.input :ends_at,
              as: :string,
              input_html: { data: { controller: "datepicker" } } %>
  <%= f.submit class: "button-custom" %>
<% end %>

app/views/cars/create.html.erb
<h1>Cars#create</h1>
<p>Find me in app/views/cars/create.html.erb</p>

app/views/cars/destroy.html.erb
<h1>Cars#destroy</h1>
<p>Find me in app/views/cars/destroy.html.erb</p>

app/views/cars/index.html.erb
<div class="title">
  <h2><strong>All cars</strong></h2>
  <h5>Choose one that suits you:</h5>
</div>
<div class="car-grid">
  <% @cars.each do |car|%>
    <div id="link-card"><%= link_to car_path(car) do %></div>
      <div class="car-card">
        <div class="align-self-center">
          <div id="brand">
            <h3 class="align-self-center"><%= car.brand %></h3>
          </div>
          <div id="model">
            <p class="align-self-center"><%= car.model %></p>
          </div>
          <div id="price_per_day">
            <p class="align-self-center"><strong><%= car.price_per_day %>/jour</strong></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/cars/show.html.erb
<div class="flexbox">
  <div class="flex-items">
    <h2> Take a closer look </h2>
  </div>
  <div class="flex-items">
    <h3><%= @car.brand %> - <%= @car.model %></h3>
  </div>
  <div class="flex-items">
    <%= link_to "Back to cars", cars_path, class: "button-back" %>
  </div>
  <div class="flex-items">
    <p>Rent this car for only <%= @car.price_per_day %> a day !</p>
  </div>
  <div class="flex-items">
    <p>Initial traffic release for this beauty: <%= @car.year_of_production %>.</p>
  </div>
  <div class="flex-items">
    <%= link_to "Book", new_car_booking_path(@car), class: "button-custom" %>
  </div>
</div>

app/views/cars/update.html.erb
<h2>Cars#update</h2>
<p>Find me in app/views/cars/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRentCarsChallenge</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <% unless current_page?(root_path) %>
      <div class="containt container my-4">
        <%= yield %>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div>
    <h1>Carrently-living</h1>
    <div>
      <h4>make car renting easier.</h4>
    </div>
  </div>
</div>
<div id="home-container">
  <div class="flexbox">
    <div class="flex-items">
      <h3><strong>Cars fit to your needs</strong></h3>
    </div>
    <div class="flex-items">
      <h5>Take a quick look at our offers down here:</h5>
    </div>
    <div class="flex-items">
      <%= link_to "Cars", cars_path, class: "big-button"%>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item ms-3 dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>